defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

name: conversion_test

input_path: bags/combined
output_path: bags/converted/${name}
rate: 10.0 # Hz
image_shape: [240, 320, 3] # HWC

joint_states:
  - topic: /omnid1/joint/joint_states
    joints:
      - name: before_1
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: after_1
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: before_2
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: after_2
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: before_3
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: after_3
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: x
        position: low_dim
        velocity: low_dim
        effort: action
      - name: y
        position: low_dim
        velocity: low_dim
        effort: action
      - name: z
        position: low_dim
        velocity: low_dim
        effort: action
      - name: gimbal_x
        position: low_dim
      - name: gimbal_y
        position: low_dim
      - name: gimbal_z
        position: low_dim

twists:
  - topic: /omnid1/cmd_vel
    linear:
      x: low_dim
      y: low_dim
    angular:
      z: low_dim

images:
  - topic: /overhead_camera/color/image_raw/compressed
    shape: ${image_shape}
  - topic: /horizontal_camera/color/image_raw/compressed
    shape: ${image_shape}
  - topic: /onboard_camera/color/image_raw/compressed
    shape: ${image_shape}

hydra:
  output_subdir: null
  run:
    dir: .