defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

name: conversion_test

input_path: bags/combined
output_path: bags/converted/${name}
rate: 10 # Hz

joint_states:
  - topic: /omnid1/joint/joint_states
    joints:
      - name: before_1
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: after_1
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: before_2
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: after_2
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: before_3
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: after_3
        position: low_dim
        velocity: low_dim
        effort: low_dim
      - name: x
        position: low_dim
        velocity: low_dim
        effort: action
      - name: y
        position: low_dim
        velocity: low_dim
        effort: action
      - name: z
        position: low_dim
        velocity: low_dim
        effort: action
      - name: gimbal_x
        position: low_dim
      - name: gimbal_y
        position: low_dim
      - name: gimbal_z
        position: low_dim


hydra:
  output_subdir: null
  run:
    dir: .