name: lowdim_input_ee_gimbal_output_position_50Hz

input_path: ../../bags/combined
output_path: ../../bags/converted/${task.data_conversion.name}
rate: 50.0 # Hz

joint_states:
  - topic: /omnid1/joint/joint_states
    joints:
      - name: x
        position:
          - action
          - low_dim
        velocity:
          - low_dim
        effort:
          - low_dim
      - name: y
        position:
          - action
          - low_dim
        velocity:
          - low_dim
        effort:
          - low_dim
      - name: z
        position:
          - action
          - low_dim
        velocity:
          - low_dim
        effort:
          - low_dim
      - name: gimbal_x
        position:
          - low_dim
      - name: gimbal_y
        position:
          - low_dim
      - name: gimbal_z
        position:
          - low_dim