defaults:
  - _self_
  - data_conversion: image_input_ee_gimbal_output_force_15Hz

name: omnid_image_input_ee_gimbal_output_force

dataset_path: ../../bags/converted/${task.data_conversion.name}

# Shapes must match the data conversion config file
image_shape: &image_shape ${task.data_conversion.image_shape}
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    overhead_camera:
      shape: *image_shape
      type: rgb
    horizontal_camera:
      shape: *image_shape
      type: rgb
    onboard_camera:
      shape: *image_shape
      type: rgb
    low_dim_obs:
      shape: [12]
      type: low_dim
  action:
    shape: [3]

env_runner:
  _target_: diffusion_policy.env_runner.omnid_image_runner.OmnidImageRunner

dataset:
  _target_: diffusion_policy.dataset.omnid_image_dataset.OmnidImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${n_obs_steps}
  n_latency_steps: ${n_latency_steps}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null