defaults:
  - _self_
  - data_conversion: conversion_test

name: omnid_lowdim

dataset_path: ../../bags/converted/conversion_test

# Shapes must match the "bags" conversion config file
obs_dim: 33
action_dim: 3
keypoint_dim: 0

env_runner:
  _target_: diffusion_policy.env_runner.omnid_lowdim_runner.OmnidLowdimRunner

dataset:
  _target_: diffusion_policy.dataset.omnid_lowdim_dataset.OmnidLowdimDataset
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${n_obs_steps}
  n_latency_steps: ${n_latency_steps}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null